"""
ml_model.py
-----------
Machine-Learning forecasting engine for the Network Capacity Planning System.

Approach
--------
* Uses Random Forest Regressor (primary) trained on time-series features
  engineered from the historical metrics table.
* Features: hour-of-day, day-of-week, day-index, rolling means (3 & 6 steps),
  lag-1, lag-2, lag-3 values, device-type encoding.
* Evaluated with MAE, RMSE, and R² metrics.
* Future predictions are generated by recursively feeding model output
  back as lag features.

Why Random Forest?
------------------
- Handles non-linear daily/weekly seasonality without explicit decomposition.
- Robust to the spikes present in network traffic data.
- No GPU required; trains on 7,200+ rows in <5 seconds on typical hardware.
- Feature importances give explainability suitable for a Wipro demo.
"""

import os
import pickle
import warnings
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

warnings.filterwarnings("ignore")

MODEL_DIR  = "models"
MODEL_FILE = os.path.join(MODEL_DIR, "forecasting_model.pkl")
DB_PATH    = os.path.join("database", "network.db")

RESOURCE_COLUMNS = {
    "cpu":       "cpu_utilization",
    "memory":    "memory_utilization",
    "bandwidth": "bandwidth_utilization",
    "traffic":   "network_traffic",
}

# Encode device types to integers
DEVICE_TYPE_MAP = {
    "Router": 0, "Switch": 1, "Firewall": 2,
    "Server": 3, "Access Point": 4,
}


# ── Feature engineering ──────────────────────────────────────────────────────

def build_features(df: pd.DataFrame, target_col: str) -> pd.DataFrame:
    """
    Add time-based and lag features to a per-device time-series DataFrame.
    df must have columns: timestamp (datetime), target_col, device_type_enc.
    """
    df = df.copy().sort_values("timestamp").reset_index(drop=True)
    df["hour"]      = df["timestamp"].dt.hour
    df["dow"]       = df["timestamp"].dt.dayofweek
    df["month"]     = df["timestamp"].dt.month
    df["day_index"] = (df["timestamp"] - df["timestamp"].min()).dt.days

    # Lag features
    for lag in [1, 2, 3, 6]:
        df[f"lag_{lag}"] = df[target_col].shift(lag)

    # Rolling statistics
    df["roll_mean_3"] = df[target_col].shift(1).rolling(3,  min_periods=1).mean()
    df["roll_mean_6"] = df[target_col].shift(1).rolling(6,  min_periods=1).mean()
    df["roll_std_3"]  = df[target_col].shift(1).rolling(3,  min_periods=1).std().fillna(0)

    df = df.dropna()
    return df


FEATURE_COLS = [
    "hour", "dow", "month", "day_index",
    "lag_1", "lag_2", "lag_3", "lag_6",
    "roll_mean_3", "roll_mean_6", "roll_std_3",
    "device_type_enc",
]


# ── Data loading ─────────────────────────────────────────────────────────────

def load_data_from_db(resource: str) -> pd.DataFrame:
    """Load metrics + device type from SQLite for the given resource."""
    from database import get_connection
    col = RESOURCE_COLUMNS.get(resource, "cpu_utilization")
    conn = get_connection()
    query = f"""
        SELECT m.device_id, m.timestamp, m.{col} AS target,
               d.device_type
        FROM   network_metrics m
        JOIN   devices d ON d.id = m.device_id
        ORDER  BY m.device_id, m.timestamp
    """
    df = pd.read_sql_query(query, conn)
    conn.close()
    df["timestamp"] = pd.to_datetime(df["timestamp"])
    df["device_type_enc"] = df["device_type"].map(DEVICE_TYPE_MAP).fillna(0).astype(int)
    return df


def load_device_data(device_id: int, resource: str) -> pd.DataFrame:
    """Load metrics for a single device."""
    from database import get_connection
    col = RESOURCE_COLUMNS.get(resource, "cpu_utilization")
    conn = get_connection()
    query = f"""
        SELECT m.device_id, m.timestamp, m.{col} AS target,
               d.device_type
        FROM   network_metrics m
        JOIN   devices d ON d.id = m.device_id
        WHERE  m.device_id = ?
        ORDER  BY m.timestamp
    """
    df = pd.read_sql_query(query, conn, params=(device_id,))
    conn.close()
    df["timestamp"] = pd.to_datetime(df["timestamp"])
    df["device_type_enc"] = df["device_type"].map(DEVICE_TYPE_MAP).fillna(0).astype(int)
    return df


# ── Training ─────────────────────────────────────────────────────────────────

def train_model(resource: str = "cpu", force: bool = False):
    """
    Train a Random Forest on all devices for a given resource metric.
    Saves the model to disk and returns evaluation metrics.
    """
    model_path = os.path.join(MODEL_DIR, f"model_{resource}.pkl")
    if os.path.exists(model_path) and not force:
        print(f"  Model for '{resource}' already exists — skipping training.")
        return load_model_meta(resource)

    print(f"  Training model for resource: {resource} …")
    df_raw = load_data_from_db(resource)
    if df_raw.empty:
        raise ValueError("No data found in database. Run generate_dataset.py first.")

    # Build features per device then concatenate
    frames = []
    for dev_id, grp in df_raw.groupby("device_id"):
        feat = build_features(grp, "target")
        frames.append(feat)
    df = pd.concat(frames, ignore_index=True)

    X = df[FEATURE_COLS]
    y = df["target"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, shuffle=False
    )

    rf = RandomForestRegressor(
        n_estimators=150,
        max_depth=12,
        min_samples_leaf=5,
        random_state=42,
        n_jobs=-1,
    )
    rf.fit(X_train, y_train)
    y_pred = rf.predict(X_test)

    mae  = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2   = r2_score(y_test, y_pred)

    meta = {
        "resource":      resource,
        "model_type":    "RandomForestRegressor",
        "n_estimators":  150,
        "train_samples": len(X_train),
        "test_samples":  len(X_test),
        "mae":           round(mae,  4),
        "rmse":          round(rmse, 4),
        "r2":            round(r2,   4),
        "feature_importances": dict(zip(FEATURE_COLS, rf.feature_importances_.round(4).tolist())),
        "trained_at":    datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    }

    os.makedirs(MODEL_DIR, exist_ok=True)
    with open(model_path, "wb") as f:
        pickle.dump({"model": rf, "meta": meta}, f)

    print(f"  [OK] {resource.upper()} model — MAE={mae:.2f}  RMSE={rmse:.2f}  R2={r2:.4f}")
    return meta


def load_model_meta(resource: str) -> dict:
    model_path = os.path.join(MODEL_DIR, f"model_{resource}.pkl")
    if not os.path.exists(model_path):
        return {}
    with open(model_path, "rb") as f:
        data = pickle.load(f)
    return data.get("meta", {})


def load_trained_model(resource: str):
    model_path = os.path.join(MODEL_DIR, f"model_{resource}.pkl")
    if not os.path.exists(model_path):
        raise FileNotFoundError(f"Model for '{resource}' not found. Run train_all_models() first.")
    with open(model_path, "rb") as f:
        data = pickle.load(f)
    return data["model"]


def train_all_models(force: bool = False) -> dict:
    """Train models for all 4 resource types. Returns combined metrics."""
    all_meta = {}
    for resource in RESOURCE_COLUMNS:
        try:
            meta = train_model(resource, force=force)
            all_meta[resource] = meta
        except Exception as e:
            print(f"  [ERROR] Failed to train {resource}: {e}")
            all_meta[resource] = {"error": str(e)}
    return all_meta


# ── Forecasting ──────────────────────────────────────────────────────────────

def forecast(device_id: int, resource: str, days: int = 7) -> dict:
    """
    Generate future predictions for a device and resource over `days` days.
    Returns a dict with historical and predicted series.
    """
    col      = RESOURCE_COLUMNS.get(resource, "cpu_utilization")
    df_raw   = load_device_data(device_id, resource)

    if df_raw.empty:
        raise ValueError(f"No data for device {device_id}")

    # Build features on historical data
    df_feat  = build_features(df_raw, "target")
    model    = load_trained_model(resource)

    # Last known state for recursive forecasting
    last_ts      = df_raw["timestamp"].max()
    dev_type_enc = df_raw["device_type_enc"].iloc[0]
    historical   = df_raw["target"].tolist()

    # Use last N values as seed for lag features
    seed_vals = df_feat["target"].tolist()
    if len(seed_vals) < 6:
        seed_vals = [50.0] * 6

    predictions  = []
    future_dates = []
    lag_buffer   = list(seed_vals[-6:])   # [oldest … newest]

    step_hours   = 2   # match dataset cadence
    total_steps  = (days * 24) // step_hours

    roll_mean_3  = np.mean(lag_buffer[-3:])
    roll_mean_6  = np.mean(lag_buffer[-6:])
    roll_std_3   = np.std(lag_buffer[-3:])

    day_offset   = (last_ts - df_raw["timestamp"].min()).days

    for step in range(total_steps):
        ts = last_ts + timedelta(hours=(step + 1) * step_hours)
        feat = np.array([[
            ts.hour,
            ts.dayofweek,
            ts.month,
            day_offset + (step * step_hours) // 24,
            lag_buffer[-1],
            lag_buffer[-2],
            lag_buffer[-3],
            lag_buffer[-6],
            roll_mean_3,
            roll_mean_6,
            roll_std_3,
            dev_type_enc,
        ]], dtype=np.float64)
        pred_val = float(model.predict(feat)[0])
        pred_val = round(np.clip(pred_val, 0, 100 if resource != "traffic" else None), 2)

        predictions.append(pred_val)
        future_dates.append(ts.strftime("%Y-%m-%d %H:%M"))

        # Update rolling buffers
        lag_buffer.append(pred_val)
        if len(lag_buffer) > 6:
            lag_buffer = lag_buffer[-6:]
        roll_mean_3 = np.mean(lag_buffer[-3:])
        roll_mean_6 = np.mean(lag_buffer)
        roll_std_3  = np.std(lag_buffer[-3:])

    # Historical summary — last 30 days
    hist_df = df_raw.tail(min(len(df_raw), 360))
    hist_dates  = hist_df["timestamp"].dt.strftime("%Y-%m-%d %H:%M").tolist()
    hist_values = hist_df["target"].round(2).tolist()

    peak_pred = round(float(np.max(predictions)), 2)
    avg_pred  = round(float(np.mean(predictions)), 2)

    # Risk level based on predicted peak
    if peak_pred >= 85:
        risk = "CRITICAL"
    elif peak_pred >= 70:
        risk = "HIGH"
    elif peak_pred >= 55:
        risk = "MEDIUM"
    else:
        risk = "LOW"

    return {
        "device_id":        device_id,
        "resource":         resource,
        "days":             days,
        "historical_dates": hist_dates,
        "historical_values":hist_values,
        "forecast_dates":   future_dates,
        "forecast_values":  predictions,
        "peak_predicted":   peak_pred,
        "avg_predicted":    avg_pred,
        "risk_level":       risk,
    }


# ── Capacity analysis ─────────────────────────────────────────────────────────

def capacity_analysis(device_id: int, days: int = 30) -> dict:
    """
    Run forecast for all resources and compare against capacity thresholds.
    Returns capacity status and recommendations per resource.
    """
    results = {}
    for resource in RESOURCE_COLUMNS:
        try:
            fc = forecast(device_id, resource, days)
            peak  = fc["peak_predicted"]
            avg   = fc["avg_predicted"]

            if resource == "traffic":
                status = "SAFE"      # traffic doesn't have % capacity in same way
            elif peak >= 85:
                status = "CRITICAL"
            elif peak >= 70:
                status = "WARNING"
            else:
                status = "SAFE"

            # Growth estimate
            hist_recent = fc["historical_values"]
            if len(hist_recent) > 12:
                growth = ((hist_recent[-1] - hist_recent[-12]) / max(hist_recent[-12], 1)) * 100
            else:
                growth = 0.0

            results[resource] = {
                "peak_predicted":  peak,
                "avg_predicted":   avg,
                "status":          status,
                "growth_pct":      round(growth, 2),
                "recommendation":  _recommend(resource, peak, growth),
            }
        except Exception as e:
            results[resource] = {"error": str(e)}
    return results


def _recommend(resource: str, peak: float, growth: float) -> str:
    labels = {"cpu": "CPU", "memory": "Memory", "bandwidth": "Bandwidth", "traffic": "Traffic"}
    name   = labels.get(resource, resource.title())
    if resource == "traffic":
        if growth > 20:
            return "Monitor network traffic — significant growth detected."
        return "Traffic within normal range."
    if peak >= 85:
        return f"URGENT: {name} utilization critical. Immediate capacity expansion required."
    elif peak >= 70:
        return f"WARNING: {name} approaching capacity limit. Plan upgrade within 30 days."
    elif growth > 15:
        return f"Monitor {name} usage — growth trend detected. Consider proactive scaling."
    return f"No immediate action required for {name}."


# ── Alert generation ─────────────────────────────────────────────────────────

def generate_alerts(device_id: int = None) -> list:
    """
    Generate risk alerts by running forecasts for all devices (or one device).
    Saves alerts to DB.
    """
    from database import get_connection
    conn = get_connection()
    c    = conn.cursor()

    # Get device list
    if device_id:
        devices = c.execute(
            "SELECT id, device_name FROM devices WHERE id=?", (device_id,)
        ).fetchall()
    else:
        devices = c.execute("SELECT id, device_name FROM devices").fetchall()

    alerts = []
    for dev in devices:
        dev_id, dev_name = dev[0], dev[1]
        for resource in RESOURCE_COLUMNS:
            try:
                fc = forecast(dev_id, resource, days=7)
                peak = fc["peak_predicted"]
                avg  = fc["avg_predicted"]
                risk = fc["risk_level"]
                hist = fc["historical_values"]
                curr = hist[-1] if hist else 0

                if risk in ("HIGH", "CRITICAL"):
                    rec  = _recommend(resource, peak, 0)
                    msg  = (
                        f"{dev_name} {resource.title()} utilization predicted to reach "
                        f"{peak}% in the next 7 days (current: {curr}%)."
                    )
                    c.execute(
                        "INSERT INTO alerts "
                        "(device_id, device_name, resource, current_value, predicted_value, "
                        " risk_level, message, recommendation, status) "
                        "VALUES (?,?,?,?,?,?,?,?,?)",
                        (dev_id, dev_name, resource.upper(), curr, peak, risk, msg, rec, "Active"),
                    )
                    alerts.append({
                        "device_id": dev_id, "device_name": dev_name,
                        "resource": resource.upper(), "current_value": curr,
                        "predicted_value": peak, "risk_level": risk,
                        "message": msg, "recommendation": rec,
                    })
            except Exception:
                pass

    conn.commit()
    conn.close()
    return alerts


# ── CLI entry point ───────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("Training all forecasting models …\n")
    metrics = train_all_models(force=True)
    print("\n=== Model Performance Summary ===")
    for resource, meta in metrics.items():
        if "error" not in meta:
            print(f"  {resource.upper():10s}  MAE={meta['mae']:.2f}  "
                  f"RMSE={meta['rmse']:.2f}  R²={meta['r2']:.4f}")
